compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmMinimalAgeGate: '7d'

npmPreapprovedPackages:
  - '@intercom/*'

npmRegistryServer: 'https://socket-firewall-registry.corporate.intercom.io/npm'

npmRegistries:
  'https://socket-firewall-registry.corporate.intercom.io/npm':
    npmAuthToken: '${SOCKET_FIREWALL_NPM_TOKEN}'
    npmAlwaysAuth: true

supportedArchitectures:
  cpu:
    - arm64
    - x64
    - darwin-x64
  os:
    - current
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.10.0.cjs
