#!/bin/bash

echo IOS_INTERCOM_APP_ID=$IOS_INTERCOM_APP_ID >>.env
echo IOS_INTERCOM_KEY=$IOS_INTERCOM_KEY >>.env
echo ANDROID_INTERCOM_APP_ID=$ANDROID_INTERCOM_APP_ID >>.env
echo ANDROID_INTERCOM_KEY=$ANDROID_INTERCOM_KEY >>.env
echo CAROUSEL_ID=$CAROUSEL_ID >>.env
echo EVENT_NAME=$EVENT_NAME >>.env
echo ARTICLE_ID=$ARTICLE_ID >>.env
echo USER_NAME=$USER_NAME >>.env
echo SEARCH_TERM=$SEARCH_TERM >>.env
echo SECTION_ID=$SECTION_ID >>.env
