#!/bin/sh

#
# Functions
#
function log() {
  echo "\n"
  echo "======================================="
  echo "$1"
  echo "======================================="
}

log "🏎️  Running React native setup script 🏎️"

log "📱 Installing xcode tools 📱"

if [ ! -f /Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib ]; then
  echo "⚠️ Xcode CommandLineTools not found installing. Please install and rerun this script ⚠️"
  xcode-select --install
  exit 1
fi
echo "Xcode CommandLineTools installed 👍"

if ! [ -x "$(command -v xcode-select)" ]; then
  echo "⚠️ You need Xcode to setup this project. Please install and rerun this script ⚠️"
  exit 1
fi

log "👀 Looking for Homebrew 👀"
if ! [ -x "$(command -v brew)" ]; then
  echo "🍺 Installing Homebrew 🍺"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  echo 'export PATH=/opt/homebrew/bin:$PATH' >> ~/.bash_profile
  echo 'export PATH=/opt/homebrew/bin:$PATH' >> ~/.zshrc
else
  echo "Homebrew already installed 👍"
fi

log "👀 Looking for rbenv 👀"
if ! [ -x "$(command -v rbenv)" ]; then
  echo "🍺 Installing rbenv with brew 🍺"
  brew install rbenv ruby-build
  echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
  echo 'eval "$(rbenv init -)"' >> ~/.zshrc
  eval "$(rbenv init -)"
else
  echo "rbenv already installed 👍"
fi

rbenv install --skip-existing
echo "Ruby setup complete 👍"

log "👀 Looking for nvm 👀"
if ! [ -x "$(command -v nvm)" ]; then
  echo "🍺 Installing nvm with brew 🍺"
  brew install nvm
fi

# Source nvm
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"

nvm install
echo "Node.js setup complete 👍"

log "👀 Looking for yarn 👀"
if ! [ -x "$(command -v yarn)" ]; then
  echo "🍺 Installing yarn 🍺"
  brew install yarn
else
  echo "yarn already installed 👍"
fi

log "📟 installing dependencies 📟"
yarn

log "📟 installing dependencies for our example app 📟"
cd example/ios
pod install
cd -

echo "You're all set up 👍"
echo "📱 Run example app on iOS using -> yarn example ios"
echo "📱 Run example app on android using -> yarn example android"
